@VectorDbDemo_HostAddress = http://localhost:5073

GET {{VectorDbDemo_HostAddress}}/version/

###

GET {{VectorDbDemo_HostAddress}}/setup/

###

POST {{VectorDbDemo_HostAddress}}/addvector/
Accept: application/json
Content-Type: application/json

{
  "Id": 6,
  "Name": "Electric Kettle",
  "Description": "A fast-boiling electric kettle with a sleek design. Perfect for quickly heating water for tea, coffee, or instant meals. Features automatic shut-off and boil-dry protection for safety."
}

###

POST {{VectorDbDemo_HostAddress}}/queryvector/
Accept: application/json
Content-Type: application/json

{
  "Text": "decor"
}

###